DEFAULT_RULES = [
    {
        "rule_code": "RULE_DOCX_KEEP_FORMAT",
        "rule_name": "禁止破坏原 DOCX 格式",
        "rule_type": "format",
        "severity": "A",
        "trigger_keywords": ["破坏原 DOCX 格式", "破坏格式", "格式被破坏"],
        "correction_strategy": "执行局部替换前先锁定样式，优先只替换文字，不重建整篇文档。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_SINGLE_CITATION",
        "rule_name": "禁止一处引用多个文献",
        "rule_type": "citation",
        "severity": "B",
        "trigger_keywords": ["一处引用多个文献", "[1][2]", "[1,2]"],
        "correction_strategy": "由 CitationAgent 拆分引用位置，确保每处正文引用只对应一个编号。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_FIGURE_NO_CROSS_LINE",
        "rule_name": "禁止图表线条交叉",
        "rule_type": "figure",
        "severity": "A",
        "trigger_keywords": ["线条交叉", "连线交叉", "交叉线"],
        "correction_strategy": "使用分层布局重新规划节点，确保连接线不交叉、节点不重叠。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_FLOW_HAS_DECISION",
        "rule_name": "禁止流程图缺少必要判断节点",
        "rule_type": "figure",
        "severity": "B",
        "trigger_keywords": ["流程图缺少判断节点", "没有判断节点", "缺少必要判断节点"],
        "correction_strategy": "为流程图补充菱形判断节点，并重新连接是/否分支。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_TABLE_THREE_LINE",
        "rule_name": "禁止表格不是三线表",
        "rule_type": "table",
        "severity": "A",
        "trigger_keywords": ["不是三线表", "表格不是三线表", "普通网格表"],
        "correction_strategy": "由 TableBuilderAgent 移除竖线和内部横线，仅保留顶线、表头线和底线。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_CONCLUSION_NOT_CHAPTER_SUMMARY",
        "rule_name": "禁止结论写成章节小结",
        "rule_type": "content",
        "severity": "B",
        "trigger_keywords": ["结论写成章节小结", "各章小结", "本章小结堆砌"],
        "correction_strategy": "重写结论为研究成果、系统不足和未来展望，不逐章复述。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_TEST_NOT_OPERATION_LOG",
        "rule_name": "禁止测试章节写成操作流水账",
        "rule_type": "content",
        "severity": "B",
        "trigger_keywords": ["测试章节写成操作流水账", "操作流水账", "流水账"],
        "correction_strategy": "按测试目标、测试环境、测试用例、结果分析组织测试章节。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_TOPIC_TECH_HARDWARE_CONSISTENCY",
        "rule_name": "禁止论文题目、技术栈、硬件型号前后不一致",
        "rule_type": "consistency",
        "severity": "A",
        "trigger_keywords": ["题目前后不一致", "技术栈不一致", "硬件型号不一致"],
        "correction_strategy": "在最终审查中统一题目、技术栈、硬件型号和功能模块名称。",
        "block_final_output": True,
    },
    {
        "rule_code": "RULE_TEACHER_COMMENT_NOT_REPEATED",
        "rule_name": "禁止老师明确批注的问题再次出现",
        "rule_type": "teacher_comment",
        "severity": "A",
        "trigger_keywords": ["老师批注问题再次出现", "忽略老师批注", "批注未处理"],
        "correction_strategy": "TeacherCommentAgent 必须逐条确认批注已转为返工任务并完成复查。",
        "block_final_output": True,
    },
]
