DEFAULT_RULES = [
    ("RULE_DOCX_KEEP_FORMAT", ["DOCX", "格式"], "禁止破坏原 DOCX 格式", "A", True),
    ("RULE_SCOPE_PROTECTION", ["局部修改", "章节"], "禁止修改用户未授权章节", "A", True),
    ("RULE_FIGURE_NO_CROSS_LINE", ["流程图", "架构图", "ER图"], "连接线不得交叉，节点不得重叠，必须使用分层布局", "A", True),
    ("RULE_FLOW_HAS_DECISION", ["流程图"], "流程图必须包含必要判断节点", "B", True),
    ("RULE_TABLE_THREE_LINE", ["表格", "三线表"], "表格默认采用三线表", "A", True),
    ("RULE_CITATION_ORDER", ["参考文献", "引用"], "禁止参考文献编号错乱", "A", True),
    ("RULE_SINGLE_CITATION", ["引用"], "禁止一处引用多个文献", "B", True),
    ("RULE_TOPIC_CONSISTENCY", ["题目", "技术栈", "硬件型号"], "禁止论文题目、技术栈、硬件型号前后不一致", "A", True),
    ("RULE_ABSTRACT_STRUCTURED", ["摘要"], "禁止摘要写成一整段无结构内容", "B", True),
    ("RULE_CONCLUSION_NOT_SUMMARY", ["结论"], "禁止结论写成各章小结", "B", True),
    ("RULE_TEST_NOT_LOG", ["测试章节", "系统测试"], "禁止测试章节写成操作流水账", "B", True),
    ("RULE_DB_FIELD_CONCISE", ["数据库字段"], "禁止数据库表字段说明过长", "C", False),
    ("RULE_REQUIREMENT_NOT_IMPLEMENTATION", ["需求分析"], "禁止需求分析写成系统实现", "B", True),
    ("RULE_TECH_NOT_WIKI", ["相关技术"], "禁止相关技术写成百科介绍", "B", True),
    ("RULE_ACADEMIC_TONE", ["正文"], "禁止正文中出现明显口语化表达", "B", True),
    ("RULE_PROJECT_MATCH", ["功能模块"], "禁止生成与项目不符的功能模块", "A", True),
    ("RULE_TEACHER_COMMENT_REQUIRED", ["老师批注"], "禁止忽略老师批注", "A", True),
    ("RULE_FINAL_REVIEW_REQUIRED", ["导出"], "禁止最终导出前不做审查", "A", True),
]
